### ISSUE TITLE
archive password

### ISSUE THREAD

**Issue by vickyvivian1621** [CKevens/CobaltStrike-4.8-Cracked#5]
the archive password is not correct

**Comment by SiongokBrian** [comment]
![Capture112](https://github.com/CKevens/CobaltStrike-4.8-Cracked/assets/57943998/4f236237-c5a8-4af0-8433-afcaf5b3c145)
on wevul the webmaster is saying the folder password is on github but I can't figure where it is.

**Comment by P4x1s** [comment]
www.wevul.com
